### ISSUE TITLE
django 의 변수 관리

### ISSUE THREAD

**Issue by pai-plznw4me** [pai-seocho/school-management-system#5]
1. school_management_app/login 을 한후 home 으로 redirect 한다. 
```python
def login(request):
    return render(request, 'school_management_app/login.html')
# settings
LOGIN_REDIRECT_URL = 'school_management_app:home'
```

2. home 에서 `'school_management_app/index.html'` 을 rendering 한다. 
```python
def home(request):
    # login 성공시 main 관리 페이지 이동
    if request.user.is_authenticated:
        return render(request, 'school_management_app/index.html')
    # login 실패시 main 페이지로 이동
    else:
        return render(request, 'school_management_app/main.html'
```
rendering 된 html 인데 
```html
...
                        <div class="admin-title">
                            <h5 class="item-title">{{user.username}}</h5>
                            <span>Admin</span>

```
여기서 user 을 `render.context` 로 넘겨준적이 없다. 그런데 정상적으로 작동한다. 어떻게 저게 가능하지?

**Comment by pai-plznw4me** [comment]
django auth 에서 기본으로 제공할수도 있다.

**Comment by JeongtaekLim** [comment]
리서치를 조금 해보았습니다. 몇 가지 흥미로운 점들을 발견했습니다.
# 주제 정의
* 우리가 관심이 있는 주제는 __Template에 우리가 직접 주입하지 않은 user 객체가 어떻게 주입되었나.__ 로 다시 생각할 수 있습니다.
* 이 질문에 답을 하기 위해서는 Django의 요청 및 응답에 대한 대략적인 흐름부터 이해해야 함을 리서치 결과 파악했습니다.

# Django Response 및 Request Flow
* Django response 및 request 전주기적 다이어그램은 아래와 같습니다.
* 우측 하단의 `Your code`, `Extendable`, `External`, `Django` 를 먼저 보아야 합니다. 
* Template 이라고 적힌 것은 Your Code 색상으로 표기되어 있으며, .html 파일로 개발자가 작성하는 파일로 생각됩니다.
* 전 주기 그림에서는 Context가 8번 화살표에서 View로 주입되고 있음을 파악할 수 있습니다.

![image](https://user-images.githubusercontent.com/10667416/160270267-3f6a5c6d-af20-43c3-b150-4ee177ef70d6.png)
# Django Request Context
* Django 공식 [Document](https://docs.djangoproject.com/en/4.0/ref/templates/api/#using-requestcontext)를 살펴보면, 위에서 우리가 추측한 Context로 주입되는 것에 대한 보다 상세한 내용을 알 수 있습니다.
* Context 들은 context processors에 의해 주입되며 context processors들은 settings.py에 정의되어 있다고 합니다.
    ```py
        [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ]
    ```
* 위 코드에서 django.contrib.auth.context_processors.auth 가 user를 주입하고 있음을 추측할 수 있습니다.
* 이를 명확하게 증명하기 위해서는 django.contrib.auth.context_processors.auth 구문을 settings.py에서 제거하고, Django를 실행시켜 보면 보다 명확할 수 있을 것으로 예상됩니다.

# 최종 테스트
* 이를 테스트해보려고 이 프로젝트 fork 후 makemigrations 및 migrate 진행 후 runserver 실행했으나, 아래 에러가 발생해서 최종 테스트는 못했습니다..
* ![image](https://user-images.githubusercontent.com/10667416/160270957-931cb146-b405-47fa-b116-57105d0522e2.png)
